/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CardComponent {
        "name": string;
    }
    interface GButton {
        "disabled": boolean;
        "text": string;
    }
}
declare global {
    interface HTMLCardComponentElement extends Components.CardComponent, HTMLStencilElement {
    }
    var HTMLCardComponentElement: {
        prototype: HTMLCardComponentElement;
        new (): HTMLCardComponentElement;
    };
    interface HTMLGButtonElement extends Components.GButton, HTMLStencilElement {
    }
    var HTMLGButtonElement: {
        prototype: HTMLGButtonElement;
        new (): HTMLGButtonElement;
    };
    interface HTMLElementTagNameMap {
        "card-component": HTMLCardComponentElement;
        "g-button": HTMLGButtonElement;
    }
}
declare namespace LocalJSX {
    interface CardComponent {
        "name"?: string;
    }
    interface GButton {
        "disabled"?: boolean;
        "text"?: string;
    }
    interface IntrinsicElements {
        "card-component": CardComponent;
        "g-button": GButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "card-component": LocalJSX.CardComponent & JSXBase.HTMLAttributes<HTMLCardComponentElement>;
            "g-button": LocalJSX.GButton & JSXBase.HTMLAttributes<HTMLGButtonElement>;
        }
    }
}
