/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CardComponent {
        "name": string;
    }
    interface GButton {
        "disabled": boolean;
        "text": string;
    }
    interface GTab {
        "active": boolean;
        "disabled": boolean;
        "label": string;
    }
    interface GTabs {
        "openTab": (index: number) => Promise<void>;
    }
}
declare global {
    interface HTMLCardComponentElement extends Components.CardComponent, HTMLStencilElement {
    }
    var HTMLCardComponentElement: {
        prototype: HTMLCardComponentElement;
        new (): HTMLCardComponentElement;
    };
    interface HTMLGButtonElement extends Components.GButton, HTMLStencilElement {
    }
    var HTMLGButtonElement: {
        prototype: HTMLGButtonElement;
        new (): HTMLGButtonElement;
    };
    interface HTMLGTabElement extends Components.GTab, HTMLStencilElement {
    }
    var HTMLGTabElement: {
        prototype: HTMLGTabElement;
        new (): HTMLGTabElement;
    };
    interface HTMLGTabsElement extends Components.GTabs, HTMLStencilElement {
    }
    var HTMLGTabsElement: {
        prototype: HTMLGTabsElement;
        new (): HTMLGTabsElement;
    };
    interface HTMLElementTagNameMap {
        "card-component": HTMLCardComponentElement;
        "g-button": HTMLGButtonElement;
        "g-tab": HTMLGTabElement;
        "g-tabs": HTMLGTabsElement;
    }
}
declare namespace LocalJSX {
    interface CardComponent {
        "name"?: string;
    }
    interface GButton {
        "disabled"?: boolean;
        "text"?: string;
    }
    interface GTab {
        "active"?: boolean;
        "disabled"?: boolean;
        "label"?: string;
    }
    interface GTabs {
        "onChange"?: (event: CustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "card-component": CardComponent;
        "g-button": GButton;
        "g-tab": GTab;
        "g-tabs": GTabs;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "card-component": LocalJSX.CardComponent & JSXBase.HTMLAttributes<HTMLCardComponentElement>;
            "g-button": LocalJSX.GButton & JSXBase.HTMLAttributes<HTMLGButtonElement>;
            "g-tab": LocalJSX.GTab & JSXBase.HTMLAttributes<HTMLGTabElement>;
            "g-tabs": LocalJSX.GTabs & JSXBase.HTMLAttributes<HTMLGTabsElement>;
        }
    }
}
